// build the sinhala character n-gram model used to rank singlish matches (singlish-model.js)
// trained on the word lists made by extract-corpus.mjs
// usage: node scripts/build-model.mjs [--order=3] [--minCount=2] [--weight=log] [--step=0.5] [--out=singlish-model.js] [--holdout]
//   holdout - leave out the gold words (build-gold.mjs) to check that the eval is not overfitted
//   step - quantization step of the bits, weight - how much a word contributes: log = 1 + ln(freq), type = 1, token = freq
import fs from 'node:fs'
import zlib from 'node:zlib'

const args = Object.fromEntries(process.argv.slice(2).map(a => a.replace(/^--/, '').split('=')))
const order = +(args.order || 3), minCount = +(args.minCount || 2), weightMode = args.weight || 'log'
const outFile = new URL(`../${args.out || 'singlish-model.js'}`, import.meta.url).pathname
const dataDir = new URL('../data/', import.meta.url).pathname
const bitsStep = +(args.step || 0.5) // quantization step of the -log2 probabilities
const weightOf = { log: f => 1 + Math.log(f), type: () => 1, token: f => f }[weightMode]

const heldOut = new Set('holdout' in args ? fs.readFileSync(`${dataDir}gold.tsv`, 'utf8').trim().split('\n').map(l => l.split('\t')[2]) : [])

// counts[k] maps a context of k letters to a map of next letter -> weighted count
const counts = Array.from({ length: order }, () => new Map())
for (const slice of ['text', 'dict', 'headings']) {
	for (const line of fs.readFileSync(`${dataDir}${slice}.tsv`, 'utf8').trim().split('\n')) {
		const [word, freq] = line.split('\t'), weight = weightOf(+freq)
		if (heldOut.has(word)) continue
		const letters = '^' + word.replace(/\u200D/g, '') // ^ marks the word start
		for (let i = 1; i < letters.length; i++) {
			for (let k = 0; k < order && k <= i; k++) {
				const context = letters.slice(i - k, i), next = counts[k].get(context) || new Map()
				next.set(letters[i], (next.get(letters[i]) || 0) + weight)
				counts[k].set(context, next)
			}
		}
	}
}

// each letter is written as one ascii symbol and each probability as one symbol (quantized bits)
const symbols = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#%&()*+,-./:;<=>?@[]^_{|}~'
const letters = [...new Set([...counts[1].keys()].concat(...[...counts[0].values()].map(m => [...m.keys()])))].sort()
if (letters.length > symbols.length) throw new Error(`too many letters ${letters.length}`)
const letterSymbol = Object.fromEntries(letters.map((l, i) => [l, symbols[i]]))
const maxLevel = symbols.length - 1

// one line per order, a space separated group per context: context symbols followed by (letter, bits) pairs
const lines = counts.map((contexts, k) => {
	const groups = []
	for (const [context, next] of [...contexts].sort()) {
		const total = [...next.values()].reduce((a, c) => a + c, 0)
		const pairs = [...next].filter(([, c]) => k < 2 || c >= minCount).sort()
			.map(([l, c]) => letterSymbol[l] + symbols[Math.min(maxLevel, Math.round(-Math.log2(c / total) / bitsStep))])
		if (pairs.length) groups.push([...context].map(l => letterSymbol[l]).join('') + pairs.join(''))
	}
	return groups.join(' ')
})

const source = `// generated by scripts/build-model.mjs (order ${order}, minCount ${minCount}, weight ${weightMode}) - do not edit
export const model = {
	order: ${order},
	bitsStep: ${bitsStep},
	symbols: ${JSON.stringify(symbols)},
	letters: ${JSON.stringify(letters.join(''))},
	data: ${JSON.stringify(lines)},
}
`
fs.writeFileSync(outFile, source)
console.log(`order ${order}, minCount ${minCount}, weight ${weightMode}: ${letters.length} letters, ` +
	`contexts ${lines.map(l => l.split(' ').length).join('/')}, ${(source.length / 1024).toFixed(0)} KB, ` +
	`${(zlib.gzipSync(source).length / 1024).toFixed(1)} KB gzipped`)
